require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'test/**/*'
    - 'Gemfile'
    - 'tmp/**/*'
    - 'Rakefile'
    - 'config.ru'


Documentation:
  Enabled: false

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 3000

Metrics/LineLength:
  Max: 125

Metrics/MethodLength:
  Max: 215

Metrics/ModuleLength:
  Max: 1500

Metrics/BlockLength:
  Max: 1500

Style/RescueModifier:
  Description: 'Avoid using rescue in its modifier form.'
  StyleGuide: '#no-rescue-modifiers'
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 110

Metrics/CyclomaticComplexity:
  Max: 110

Metrics/AbcSize:
  Max: 500

Style/EmptyMethod:
  EnforcedStyle: expanded

Bundler/OrderedGems:
  TreatCommentsAsGroupSeparators: true

Style/AccessorMethodName:
  Enabled: false

Security/MarshalLoad:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Lint/MissingSuper:
  Enabled: false
